### ISSUE TITLE
Does it support mssql ?

### ISSUE THREAD

**Issue by collegeimprovements** [erlangbureau/jamdb_sybase#8]
Since there is no ecto-3 compatible lib ready for mssql, we were wondering if `jamdb_sybase` can support basic `mssql` queries!

**Comment by vstavskyi** [comment]
[tds](https://github.com/livehelpnow/tds) must be ready by now according to author's [comment](https://github.com/livehelpnow/tds/issues/90#event-2941150755)

**Comment by collegeimprovements** [comment]
thanks. closing this issue now.
